name: Static Analysis (Linting, License, Type checks...)

on:
    pull_request:
    push:
        branches:
            - trunk
            - 'release/**'
            - 'wp/**'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    check:
        name: All
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}

        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

            - uses: ./.github/action/setup-node-env

            - name: Lint JavaScript and Styles
              run: pnpm run lint

            - name: Type checking
              run: pnpm run build:package-types

            - name: Check local changes
              run: pnpm run check-local-changes

            - name: License compatibility
              run: pnpm run check-licenses
